version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s | %(levelname)-8s | %(name)s | %(correlation_id)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(correlation_id)s %(user_id)s %(endpoint)s %(message)s"

  detailed:
    format: "%(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d | %(correlation_id)s | %(user_id)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

filters:
  correlation_filter:
    (): app.core.logging.RequestContextFilter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    filters: [correlation_filter]
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filters: [correlation_filter]
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filters: [correlation_filter]
    filename: logs/app.json
    maxBytes: 10485760  # 10MB
    backupCount: 10

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filters: [correlation_filter]
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 10

  performance_file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: json
    filters: [correlation_filter]
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  app:
    level: DEBUG
    handlers: [console, file, json_file]
    propagate: False

  app.services:
    level: INFO
    handlers: [console, file, json_file]
    propagate: False

  app.core.middleware:
    level: INFO
    handlers: [console, file]
    propagate: False

  performance:
    level: WARNING
    handlers: [performance_file, console]
    propagate: False

  security:
    level: WARNING
    handlers: [error_file, console]
    propagate: False

  sqlalchemy.engine:
    level: WARNING
    handlers: [file]
    propagate: False

  # Third-party loggers
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [console, error_file]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: False

  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: False

root:
  level: INFO
  handlers: [console]